import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.barakah.app',
  appName: 'Barakah',
  webDir: 'dist',
  bundledWebRuntime: false,
  // Custom URL scheme used by the native OAuth deep link callback.
  // Android: also declared via intent-filter (generated by `npx cap sync`).
  // iOS: registered from this value.
  server: {
    hostname: 'localhost',
  },
  ios: {
    scheme: 'com.barakah.app',
    contentInset: 'always',
    infoPlist: {
      NSCameraUsageDescription: 'Barakah uses the camera to scan barcodes for halal product verification.',
      NSLocationWhenInUseUsageDescription: 'Barakah uses your location to provide prayer times and nearby place recommendations.',
    },
  },
};

export default config;
